name: Compile & Publish
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'     
        required: true
      pre_release:
        type: boolean
        description: Pre-Release?
      
  push:
    branches:
      - syntax-rewrite
  pull_request:
    branches:
      - syntax-rewrite

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - name: Switch Branch
      uses: actions/checkout@v2
      with:
        ref: 'syntax-rewrite'
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.5
    - name: Download dependencies
      run: go mod download
      
    - name: Grab CHANGELOG
      run: sed '1,/## 2021-12-16/d;/'---'/Q' CHANGELOG >> release_changelog
      
    - name: Create Release
      id: create_release
      uses: actions/create-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.version }}
        release_name: ${{ github.event.inputs.version }}
        body_path: ./release_changelog
        draft: false
        prerelease: $${{ github.event.inputs.pre_release }}
        
      
    - name: Build - Windows x64 Binary
      env:
        GOOS: windows
        GOARCH: amd64
      run: go build -ldflags "-w" -v -o ./bin/dishook_amd64.exe
      
      
    - name: Build - macOS x64 Binary
      env:
        GOOS: darwin
        GOARCH: amd64
      run: go build -ldflags "-w" -v -o ./bin/dishook_darwin_amd64
  
    - name: Build - Linux x64 Binary
      env:
        GOOS: linux
        GOARCH: amd64
      run: go build -ldflags "-w" -v -o ./bin/dishook_amd64
      
    - name: Build - Linux x86 Binary
      env:
        GOOS: linux
        GOARCH: 386
      run: go build -ldflags "-w" -v -o ./bin/dishook_386
      
    - name: Build - Linux ARM64 Binary
      env:
        GOOS: linux
        GOARCH: arm64
      run: go build -ldflags "-w" -v -o ./bin/dishook_arm64
      
    - name: Build - Linux ARM Binary
      env:
        GOOS: linux
        GOARCH: arm
      run: go build -ldflags "-w" -v -o ./bin/dishook_arm
      
  
    - name: Upload Windows amd64
      id: upload-win_amd64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./bin/dishook_amd64.exe
        asset_name: dishook_amd64.exe
        asset_content_type: application/tar+gzip
        
    - name: Upload Darwin amd64
      id: upload-darwin_amd64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./bin/dishook_darwin_amd64
        asset_name: dishook_darwin_amd64
        asset_content_type: application/tar+gzip
        
    - name: Upload Linux amd64
      id: upload-linux_amd64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./bin/dishook_amd64
        asset_name: dishook_amd64
        asset_content_type: application/tar+gzip

    - name: Upload Linux i386
      id: upload-linux_i386
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./bin/dishook_386
        asset_name: dishook_386
        asset_content_type: application/tar+gzip
  
    - name: Upload Linux ARM64
      id: upload-linux_ARM64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./bin/dishook_arm64
        asset_name: dishook_arm64
        asset_content_type: application/tar+gzip
        
    - name: Upload Linux ARM
      id: upload-linux_ARM
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./bin/dishook_arm
        asset_name: dishook_arm
        asset_content_type: application/tar+gzip
