name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.5
    - name: Download dependencies
      run: ls | go mod download
      
    - name: Build - Windows x64 Binary
      env:
        GOOS: windows
        GOARCH: amd64
      run: go build -ldflags "-w" -v -o ./bin/dishook.exe
      
    - name: Build - macOS x64 Binary
      env:
        GOOS: darwin
        GOARCH: amd64
      run: go build -ldflags "-w" -v -o ./bin/dishook_Darwin_x86_64
  
    - name: Build - Linux x64 Binary
      env:
        GOOS: linux
        GOARCH: amd64
      run: go build -ldflags "-w" -v -o ./bin/dishook_Linux_x86_64
      
    - name: Build - Linux x86 Binary
      env:
        GOOS: linux
        GOARCH: 386
      run: go build -ldflags "-w" -v -o ./bin/dishook_Linux_i386
      
    - name: Build - Linux ARM64 Binary
      env:
        GOOS: linux
        GOARCH: arm64
      run: go build -ldflags "-w" -v -o ./bin/dishook_Linux_arm64
      
    - name: Build - Linux ARM Binary
      env:
        GOOS: linux
        GOARCH: arm
      run: go build -ldflags "-w" -v -o ./bin/dishook_Linux_arm
