name: Compile

on:
  workflow_dispatch:
  push:
    branches:
      - syntax-rewrite
  pull_request:
    branches:
      - syntax-rewrite

jobs:
  compile:
    runs-on: ${{ matrix.system }}
    strategy:
      matrix:
        system: [ubuntu-latest, windows-latest, macOS-latest]
  
    steps:
    - name: Switch Branch
    - uses: actions/checkout@v2
      with:
        ref: 'syntax-rewrite'

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.5
        
    - name: Download dependencies
      run: go mod download

    - name: Build
      run: go build -v ./...
    
    - name: Create Pull Request
    - uses: peter-evans/create-pull-request@v3
      with:
        branch: syntax-rewrite
        token: ${{ secrets.PAT }}
        commit-message: Update report
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: false
        delete-branch: false
        title: 'GitHub Actions Testing'
        draft: true
