name: Compile

on:
  workflow_dispatch:
  push:
    branches:
      - syntax-rewrite
  pull_request:
    branches:
      - syntax-rewrite

jobs:
  compile:
    runs-on: ${{ matrix.system }}
    strategy:
      matrix:
        system: [ubuntu-latest, windows-latest, macOS-latest]
  
    steps:
    - name: Switch Branch
      uses: actions/checkout@v2
      with:
        ref: 'syntax-rewrite'

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.5
        
    - name: Download dependencies
      run: go mod download
      
    - name: Build and Publish - Windows
      if: ${{ matrix.system == 'windows-latest' }}
      run: go build -ldflags "-w" -v dishook | ls
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        title: "Development Build"
        files: |
          dishook.exe

    - name: Build and Publish - macOS
      if: ${{ matrix.system == 'macOS-latest' }}
      run: go build -ldflags "-w" -v dishook-macos | ls
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        title: "Development Build"
        files: |
          dishook-macos
          
    - name: Build and Publish - Linux
      if: ${{ matrix.system == 'ubuntu-latest' }}
      run: go build -ldflags "-w" -v dishook | ls
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        title: "Development Build"
        files: |
          dishook
          
    
    
