name: Compile

on:
  workflow_dispatch:
  push:
    branches:
      - syntax-rewrite
  pull_request:
    branches:
      - syntax-rewrite

jobs:
  compile:
    runs-on: ${{ matrix.system }}
    strategy:
      matrix:
        system: [ubuntu-latest, windows-latest, macOS-latest]
  
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'syntax-rewrite'

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.5
        
    - name: Download dependencies
      run: go mod download

    - name: Build
      run: go build -v ./...
